In [13]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_files
import os
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.neighbors import KNeighborsRegressor

In [2]:
%xmode Plain
%load_ext memory_profiler

Exception reporting mode: Plain


In [29]:
category = 'energy'
article_path = r'categories_articles/energy/‘I love energy,’ says trader who sees tremendous buying opportunity in the space.txt'
f = open(article_path, 'r')
f = open(article_path, 'r')
f = f.read()

data_train = load_files(os.path.join('tree_categories', category), encoding="utf-8", decode_error="replace")

labels, counts = np.unique(data_train.target, return_counts=True)
labels_sort = np.array(data_train.target_names)[labels]
c_dict = dict(zip(labels_sort, counts))
c_dict

data_train

text_train = data_train.data
y_train = data_train.target

cv = CountVectorizer(stop_words='english')
cv.fit(text_train)
X_train = cv.transform(text_train)
X_test = cv.transform([f])

rf = RandomForestClassifier(n_estimators=1000, n_jobs=-1, random_state=17)
rf.fit(X_train, y_train);

y_pred_prob = rf.predict_proba(X_test)
y_pred_prob

array([[0.088, 0.107, 0.691, 0.114]])

In [30]:
data_train.target_names

['Brent crude', 'Coal', 'Crude oil', 'Natural gas']

In [31]:
X_test.toarray()

array([[1, 0, 0, 2, 0, 0, 0, 0, 8, 1, 0, 0, 0, 0]], dtype=int64)

In [32]:
X_train.toarray()

array([[1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [33]:
cv.vocabulary_

{'barrel': 0,
 'crude': 3,
 'opec': 9,
 'oil': 8,
 'gas': 6,
 'coal': 2,
 'forties': 5,
 'oseberg': 10,
 'ekofisk': 4,
 'brent': 1,
 'urals': 13,
 'siberian': 12,
 'light': 7,
 'rebco': 11}

In [42]:
import joblib

In [43]:
joblib.dump(rf, r'economy_classifier/finance/agricult/agricult_classifier_RF.sav')
joblib.dump(cv, r'economy_classifier/finance/agricult/agricult_classifier_CV.sav')

['economy_classifier/finance/agricult/agricult_classifier_CV.sav']

In [44]:
loaded_model = joblib.load('economy_classifier/finance/agricult/agricult_classifier_RF.sav')
y_pred_loaded = loaded_model.predict_proba(X_test)
y_pred_loaded

array([[0.696, 0.1  , 0.103, 0.101]])

In [17]:
category = 'energy'
article_path = r'categories_articles/energy/‘I love energy,’ says trader who sees tremendous buying opportunity in the space.txt'
f = open(article_path, 'r')
f = open(article_path, 'r')
f = f.read()

data_train = load_files(os.path.join('tree_categories', category), encoding="utf-8", decode_error="replace")

labels, counts = np.unique(data_train.target, return_counts=True)
labels_sort = np.array(data_train.target_names)[labels]
c_dict = dict(zip(labels_sort, counts))
c_dict

data_train

text_train = data_train.data
y_train = data_train.target

cv = TfidfVectorizer(stop_words='english')
cv.fit(text_train)
X_train = cv.transform(text_train)
X_test = cv.transform([f])

rf = KNeighborsRegressor(n_neighbors=1, n_jobs=-1)
rf.fit(X_train, y_train);

y_pred_prob = rf.predict(X_test)
y_pred_prob

array([1.])