In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_files
import os
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer


In [2]:
%xmode Plain
%load_ext memory_profiler

Exception reporting mode: Plain


In [32]:
category = 'metals'
article_path = r'categories_articles/agricult/‘Age limits determined by processors and retailers’ – Creed.txt'
f = open(article_path, 'r')
f = f.read()

data_train = load_files(os.path.join('tree_categories', category), encoding="utf-8", decode_error="replace")

labels, counts = np.unique(data_train.target, return_counts=True)
labels_sort = np.array(data_train.target_names)[labels]
c_dict = dict(zip(labels_sort, counts))
c_dict

data_train

text_train = data_train.data
y_train = data_train.target

cv = CountVectorizer(stop_words='english')
cv.fit(text_train)
X_train = cv.transform(text_train)
X_test = cv.transform([f])

rf = RandomForestClassifier(n_estimators=100000, n_jobs=-1, random_state=17)
rf.fit(X_train, y_train);

y_pred_prob = rf.predict_proba(X_test)
y_pred_prob

array([[0.2512 , 0.25001, 0.24789, 0.2509 ]])

In [33]:
data_train.target_names

['Gold', 'Iron', 'Platinum', 'Silver']

In [34]:
X_test.toarray()

array([[0, 0, 0, 0]], dtype=int64)

In [35]:
cv.vocabulary_

{'platinum': 2, 'silver': 3, 'iron': 1, 'gold': 0}

In [36]:
import joblib

In [37]:
joblib.dump(rf, r'economy_classifier/finance/metals/metals_classifier_RF.sav')
joblib.dump(cv, r'economy_classifier/finance/metals/metals_classifier_CV.sav')

['economy_classifier/finance/metals/metals_classifier_CV.sav']

In [38]:
loaded_model = joblib.load('economy_classifier/finance/metals/metals_classifier_RF.sav')
y_pred_loaded = loaded_model.predict_proba(X_test)
y_pred_loaded

array([[0.2512 , 0.25001, 0.24789, 0.2509 ]])